FLAGS = -Wall -pthread -std=c++11 

Srvr:
	g++ ${FLAGS} -o CppSrvr1 CppSrvr1.cpp
	g++ ${FLAGS} -o CppSrvr2 CppSrvr2.cpp
	g++ ${FLAGS} -o CppSrvr3 CppSrvr3.cpp

SrvrOne:
	g++ ${FLAGS} -o CppSrvr1 CppSrvr1.cpp

runOne:
	./CppSrvr1
runTwo:
	./CppSrvr2
runThree:
	./CppSrvr3

clean:
	rm -f CppSrvr1
	rm -f CppSrvr2
	rm -f CppSrvr3

